// Runs the procedural generator + scheduler + automatic validation in Node
// (no browser needed) and writes a JSON + Markdown report.
// Usage: node tools/validate.mjs [--out docs/validation-report]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSchool } from '../src/building/index.js';
import { scheduleElements } from '../src/construction/schedule.js';
import { validateAndFix } from '../src/construction/validate.js';
import { FILM } from '../src/config.js';
import { MODULES } from '../src/core/modules.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const outBase = args.includes('--out') ? args[args.indexOf('--out') + 1] : null;

const t0 = Date.now();
const { ES } = await buildSchool();
const sched = scheduleElements(ES.list);
if (sched.missing.length) console.warn('UNSCHEDULED GROUPS:', sched.missing);

// first pass: validate + auto-fix; second pass: re-validate the fixed schedule
const first = validateAndFix(ES.list, { fps: FILM.fps, seconds: FILM.seconds });
const second = validateAndFix(ES.list, { fps: FILM.fps, seconds: FILM.seconds });

const summary = (r) => r.problems.map((p) => `${p.check}: ${p.count}`).join(' | ');
console.log(`elements: ${ES.list.length}, modules (unique geometries): ${MODULES.size}, build+validate ${Date.now() - t0} ms`);
console.log('PASS 1 fixes:', JSON.stringify(first.fixes, null, 1));
console.log('PASS 1 checks:', summary(first));
if (Object.keys(first.lateGroups || {}).length) console.log('PASS 1 late groups (past the hold):', first.lateGroups);
console.log('PASS 2 fixes:', JSON.stringify(second.fixes));
console.log('PASS 2 checks:', summary(second));
for (const p of second.problems) if (p.count && p.examples?.length) console.log(`  ${p.check} e.g.`, p.examples.slice(0, 4));
console.log('checkpoints:', second.checkpoints);
console.log('final state:', second.stats.finalState);
console.log('systems:', second.stats.systems);

if (outBase) {
  const base = path.resolve(ROOT, outBase);
  fs.mkdirSync(path.dirname(base), { recursive: true });
  fs.writeFileSync(`${base}.json`, JSON.stringify({ pass1: first, pass2: second }, null, 2));
  const md = [
    '# Automatic validation report', '',
    `Generated by \`node tools/validate.mjs\` — ${ES.list.length} construction elements, ${MODULES.size} unique module geometries, film ${FILM.seconds}s @ ${FILM.fps} fps.`, '',
    '## Pass 1 — automatic fixes applied', '',
    ...first.fixes.map((f) => `- **${f.rule}**: ${f.count} element(s)${f.passes ? ` (${f.passes} passes)` : ''}`), '',
    '## Pass 1 — checks', '', '| check | count |', '|---|---|',
    ...first.problems.map((p) => `| ${p.check} | ${p.count} |`), '',
    '## Pass 2 — re-validation after fixes', '',
    second.fixes.length ? second.fixes.map((f) => `- ${f.rule}: ${f.count}`).join('\n') : '- no further fixes required', '',
    '| check | count |', '|---|---|',
    ...second.problems.map((p) => `| ${p.check} | ${p.count} |`), '',
    '## Timeline checkpoints', '', '| checkpoint | frame | elements visible | permanent | complete |', '|---|---|---|---|---|',
    ...second.checkpoints.map((c) => `| ${c.name} | ${c.frame} | ${c.visible} | ${c.permanent} | ${c.complete} |`), '',
    '## Final state', '', '```json', JSON.stringify(second.stats.finalState, null, 2), '```', '',
    '## Elements per system', '', '| system | elements |', '|---|---|',
    ...Object.entries(second.stats.systems).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`), '',
  ].join('\n');
  fs.writeFileSync(`${base}.md`, md);
  console.log('wrote', `${base}.md`);
}
